resolver: lts-6.35
extra-deps:
- pandoc-1.19.2.1
- pandoc-types-1.17.0.5
- texmath-0.9.4.1
- doctemplates-0.1.0.2
- skylighting-0.1.1.5
- Graphalyze-0.15.0.0
- fgl-visualize-0.1.0.1
- language-ecmascript-analysis-0.9.1
- bktrees-0.3.1
- dotgen-0.4.2
